"""The reader's bibliography: what a persona engaged with or saved, as one .bib.

One table (`bibliography`, migration 013) and a pure render. See
docs/superpowers/specs/2026-09-30-bibliography-design.md for why.

- `fold` turns human signal into entries: a useful verdict from a person
  (`HUMAN_CLICK_SOURCES`), a full read, an explanation request. Simulated,
  bootstrap and implicit clicks never reach it -- a model reacting as the
  persona is not the reader choosing what to cite. Only papers (a DOI or an
  arXiv id) are added automatically.
- `save` / `remove` are the reader's explicit word, and win: a save revives a
  tombstone and overwrites an implicit reason; a removal is a tombstone that
  no implicit signal revives.
- A cite key is assigned once and stored, so removing one entry never
  renames another and breaks a `\\cite` already in a draft.

Nothing here commits half-way: each public writer commits once at the end.
"""

import os
import re
import sqlite3
from pathlib import Path

from attestation import library
from attestation.library import ReferenceRecord
from attestation.rank import HUMAN_CLICK_SOURCES

# fold() visits these in order and the first reason recorded stands, so on a
# first fold the strongest signal names the entry.
IMPLICIT_REASONS = ("useful", "explained", "read")
_ENGAGEMENT_REASON = {"explain": "explained", "read": "read"}

HEADER = (
    "% Generated by attestation from {name}'s bibliography; edits here are overwritten.\n"
    "% Upload your own .bib into the folder above instead. Ask the agent to save or\n"
    "% remove a paper, and this file follows.\n"
)


def reference_for_item(conn: sqlite3.Connection, item_id: int) -> int | None:
    """The library row for a feed item, created from the item if absent.
    None when no such item exists."""
    r = conn.execute(
        "SELECT id, title, url, summary, published, doi, arxiv_id FROM items WHERE id = ?",
        (item_id,),
    ).fetchone()
    if r is None:
        return None
    from attestation import citations

    rid, _ = library.upsert(
        conn,
        ReferenceRecord(
            source="feed",
            source_key=str(r["id"]),
            title=r["title"],
            year=citations._year(r["published"]),
            doi=r["doi"],
            arxiv_id=r["arxiv_id"],
            abstract=r["summary"] or None,
            url=r["url"],
        ),
    )
    return rid


def _existing(conn, user_id: int, rid: int):
    return conn.execute(
        "SELECT * FROM bibliography WHERE user_id = ? AND reference_id = ?", (user_id, rid)
    ).fetchone()


def _free_key(conn, user_id: int, rid: int) -> str:
    """bibtex_key of the row, or its first free b, c, ... suffix for this persona."""
    row = conn.execute('SELECT * FROM "references" WHERE id = ?', (rid,)).fetchone()
    base = library.bibtex_key(row)
    taken = {
        r["cite_key"]
        for r in conn.execute(
            "SELECT cite_key FROM bibliography WHERE user_id = ? AND cite_key LIKE ?",
            (user_id, base + "%"),
        )
    }
    if base not in taken:
        return base
    n = 1
    while f"{base}{chr(ord('a') + n)}" in taken:
        n += 1
    return f"{base}{chr(ord('a') + n)}"


def _insert(conn, user_id: int, rid: int, reason: str, *, removed: bool = False) -> None:
    conn.execute(
        "INSERT INTO bibliography(user_id, reference_id, cite_key, reason, removed_at)"
        " VALUES (?, ?, ?, ?, CASE WHEN ? THEN datetime('now') END)",
        (user_id, rid, _free_key(conn, user_id, rid), reason, int(removed)),
    )


def _item_ref(conn, item) -> int | None:
    """A paper item's library row, without creating one."""
    row = library.lookup_row(conn, item["doi"] or item["arxiv_id"])
    return row["id"] if row is not None else None


def _human_marks(conn, user_id: int, useful: int) -> list:
    marks = ",".join("?" * len(HUMAN_CLICK_SOURCES))
    return conn.execute(
        f"SELECT i.id, i.doi, i.arxiv_id, c.clicked_at FROM clicks c JOIN items i"
        f" ON i.id = c.item_id WHERE c.user_id = ? AND c.useful = ? AND c.source IN ({marks})"
        f" AND (i.doi IS NOT NULL OR i.arxiv_id IS NOT NULL) ORDER BY c.id",
        (user_id, useful, *sorted(HUMAN_CLICK_SOURCES)),
    ).fetchall()


def _tombstone_rejected(conn, user_id: int) -> set[int]:
    """A human "not useful" ends an implicit entry; a `saved` one stands."""
    rejected = set()
    for item in _human_marks(conn, user_id, 0):
        rejected.add(item["id"])
        rid = _item_ref(conn, item)
        if rid is not None:
            conn.execute(
                "UPDATE bibliography SET removed_at = datetime('now') WHERE user_id = ?"
                " AND reference_id = ? AND reason != 'saved' AND removed_at IS NULL",
                (user_id, rid),
            )
    return rejected


def _candidates(conn, user_id: int):
    """(item_id, reason, clicked_at) in reason-strength order."""
    for item in _human_marks(conn, user_id, 1):
        yield item["id"], "useful", item["clicked_at"]
    for kind in ("explain", "read"):
        for r in conn.execute(
            "SELECT e.item_id FROM engagement e JOIN items i ON i.id = e.item_id"
            " WHERE e.user_id = ? AND e.kind = ?"
            " AND (i.doi IS NOT NULL OR i.arxiv_id IS NOT NULL) ORDER BY e.created_at, e.item_id",
            (user_id, kind),
        ):
            yield r["item_id"], _ENGAGEMENT_REASON[kind], None


def fold(conn: sqlite3.Connection, user_id: int) -> int:
    """Turn this persona's human signal into entries; returns how many were added.

    Idempotent. A tombstone is revived only by a useful verdict made AFTER
    the removal -- the reader changing their mind -- never by a read or an
    explanation request.
    """
    rejected = _tombstone_rejected(conn, user_id)
    added = 0
    for item_id, reason, clicked_at in _candidates(conn, user_id):
        if item_id in rejected:
            continue
        rid = reference_for_item(conn, item_id)
        if rid is None:
            continue
        have = _existing(conn, user_id, rid)
        if have is None:
            _insert(conn, user_id, rid, reason)
            added += 1
        elif have["removed_at"] and clicked_at and clicked_at > have["removed_at"]:
            conn.execute(
                "UPDATE bibliography SET removed_at = NULL, reason = 'useful'"
                " WHERE user_id = ? AND reference_id = ?",
                (user_id, rid),
            )
            added += 1
    conn.commit()
    return added


def save(conn: sqlite3.Connection, user_id: int, rid: int) -> dict:
    """The reader asked to keep this one: add it, revive it, or mark it saved."""
    if _existing(conn, user_id, rid) is None:
        _insert(conn, user_id, rid, "saved")
    else:
        conn.execute(
            "UPDATE bibliography SET reason = 'saved', removed_at = NULL"
            " WHERE user_id = ? AND reference_id = ?",
            (user_id, rid),
        )
    conn.commit()
    return entry(conn, user_id, rid)


def remove(conn: sqlite3.Connection, user_id: int, rid: int) -> dict:
    """The reader asked to drop this one. A tombstone, so engagement cannot
    put it back; a paper not yet in the bibliography is tombstoned too."""
    if _existing(conn, user_id, rid) is None:
        _insert(conn, user_id, rid, "removed", removed=True)
    else:
        conn.execute(
            "UPDATE bibliography SET removed_at = coalesce(removed_at, datetime('now'))"
            " WHERE user_id = ? AND reference_id = ?",
            (user_id, rid),
        )
    conn.commit()
    return entry(conn, user_id, rid)


_ENTRY_SQL = (
    "SELECT b.cite_key, b.reason, b.added_at, b.removed_at, r.*"
    ' FROM bibliography b JOIN "references" r ON r.id = b.reference_id WHERE b.user_id = ?'
)


def _as_entry(row) -> dict:
    return {
        "key": row["cite_key"],
        "title": row["title"],
        "reason": row["reason"],
        "added_at": row["added_at"],
        "removed": row["removed_at"] is not None,
        "bibtex": library.bibtex(row, key=row["cite_key"]),
    }


def entry(conn: sqlite3.Connection, user_id: int, rid: int) -> dict:
    """One entry, live or tombstoned."""
    return _as_entry(
        conn.execute(_ENTRY_SQL + " AND b.reference_id = ?", (user_id, rid)).fetchone()
    )


def _live_rows(conn, user_id: int) -> list:
    return conn.execute(
        _ENTRY_SQL + " AND b.removed_at IS NULL ORDER BY b.rowid", (user_id,)
    ).fetchall()


def entries(conn: sqlite3.Connection, user_id: int) -> list[dict]:
    """Live entries in the order they were added."""
    return [_as_entry(r) for r in _live_rows(conn, user_id)]


def render(conn: sqlite3.Connection, user_id: int) -> str:
    """The persona's .bib. Pure over the table: the same rows render the same text."""
    name = conn.execute("SELECT name FROM users WHERE id = ?", (user_id,)).fetchone()["name"]
    body = "\n".join(library.bibtex(r, key=r["cite_key"]) for r in _live_rows(conn, user_id))
    return HEADER.format(name=name) + ("\n" + body if body else "")


def resolve_paper(conn: sqlite3.Connection, paper: str) -> int:
    """A feed item id (digits) or a library key/DOI/arXiv id, as a library row
    id. Raises LookupError with a message the caller can act on."""
    p = paper.strip()
    if p.isdigit():
        rid = reference_for_item(conn, int(p))
        if rid is None:
            raise LookupError(f"unknown item_id: {p}")
        return rid
    row = library.lookup_row(conn, p)
    if row is None:
        raise LookupError(
            f"no library reference matches {paper!r}: pass a feed item_id, or a key,"
            " DOI or arXiv id cite.search or cite.lookup returned"
        )
    return row["id"]


def keep(conn: sqlite3.Connection, user_id: int, rid: int, *, drop: bool = False) -> dict:
    """cite.save's whole act: fold, save or remove, re-render the file."""
    fold(conn, user_id)
    got = remove(conn, user_id, rid) if drop else save(conn, user_id, rid)
    path = write(conn, user_id)
    live = len(entries(conn, user_id))
    verb = "removed from" if drop else "saved to"
    return {
        "entry": got,
        "removed": got["removed"],
        "entries": live,
        # The file NAME, never the path: a machine string in every reply.
        "file": path.name if path else None,
        "message": f"{got['key']} {verb} the bibliography ({live} entries)",
    }


def output_dir() -> Path | None:
    """ATTEST_BIB_OUT, read at call time; None = inert (the table still records)."""
    configured = (os.environ.get("ATTEST_BIB_OUT") or "").strip()
    return Path(configured).expanduser() if configured else None


def file_name(name: str) -> str:
    """A persona name as a file name: `Matthew Goldey` -> `Matthew-Goldey.bib`."""
    return re.sub(r"[^A-Za-z0-9._-]+", "-", name).strip("-.") + ".bib"


def write(conn: sqlite3.Connection, user_id: int) -> Path | None:
    """Render this persona's file into ATTEST_BIB_OUT, atomically. None when unset."""
    out = output_dir()
    if out is None:
        return None
    name = conn.execute("SELECT name FROM users WHERE id = ?", (user_id,)).fetchone()["name"]
    out.mkdir(parents=True, exist_ok=True)
    path = out / file_name(name)
    tmp = path.with_suffix(".bib.tmp")
    tmp.write_text(render(conn, user_id))
    os.replace(tmp, path)
    return path


def write_all(conn: sqlite3.Connection) -> dict[str, int]:
    """Fold and write every persona that has signal or entries: {name: live entries}.
    Inert (no fold, no write) when ATTEST_BIB_OUT is unset."""
    if output_dir() is None:
        return {}
    users = conn.execute(
        "SELECT id, name FROM users WHERE id IN (SELECT user_id FROM clicks"
        " UNION SELECT user_id FROM engagement UNION SELECT user_id FROM bibliography)"
        " ORDER BY id"
    ).fetchall()
    done = {}
    for u in users:
        fold(conn, u["id"])
        # A persona whose every entry was removed still gets its (empty) file
        # rewritten, so a removal reaches the .bib.
        if conn.execute("SELECT 1 FROM bibliography WHERE user_id = ?", (u["id"],)).fetchone():
            write(conn, u["id"])
            done[u["name"]] = len(_live_rows(conn, u["id"]))
    return done
