"""Agent configs generated from `AGENT_SURFACES`, and drift detected against it.

The four `attestation-<surface>` entries in `~/.hermes/config.yaml` were typed
by hand. `install.py` writes only the single full-surface `attestation` entry
and its doctor matched on the substring "attestation", so a config with the
full server and zero surfaces reported ok -- the same false-clean the scheduler
check had before it learned to look for a second entry.

Two copies of one fact with no check between them is the whole problem, so
there is exactly one generator here and every consumer calls it, `install.py`
included. Emitting from two places to keep two files in sync would be an
embarrassing bug to reintroduce inside its own fix.

**Nothing here overwrites.** A difference between generated and on-disk is
reported with a diff and left alone; writing happens only on an explicit
`attest emit --write`. A checksum would turn a user's deliberate edit into a
warning they cannot act on, and silently rewriting it is worse. This is the
contract `_write_refresh_script` already uses ("missing or stale"), so it is
this repo's existing convention rather than a new one.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from attestation.mcp import AGENT_SURFACES, Surface

__all__ = [
    "Surface",
    "Finding",
    "hermes_servers",
    "claude_agents",
    "check_hermes",
    "parse_config_dump",
]

# The entry `install.py` writes for the whole surface. Not a surface itself, and
# reporting it as orphaned would tell the user to delete their working server.
FULL_SERVER = "attestation"
PREFIX = f"{FULL_SERVER}-"

HEADER = (
    "<!-- Generated by `attest emit` from attestation.mcp.AGENT_SURFACES."
    # `attest emit`, not `attest emit --check`. The header named a flag that
    # does not exist -- exit 2, "unrecognized arguments" -- in the one module
    # written so two copies of one fact cannot drift.
    " Edits here are reported by `attest emit`, never overwritten. -->"
)


@dataclass(frozen=True)
class Finding:
    """One disagreement between the generated config and the one on disk."""

    kind: str  # "missing" | "stale" | "orphaned"
    surface: str
    detail: str


def _dump_line(current: dict, section: str | None, indent: int, line: str) -> str | None:
    """Apply one indented line to the entry being built; return the open section.

    Split out from `parse_config_dump` to keep both under the complexity
    ratchet, and because "what does one line mean" is a separate question from
    "where does it belong".
    """
    if line.startswith("- ") and section:
        current.setdefault(section, []).append(line[2:].strip())
        return section
    if ":" not in line:
        return section

    name, _, value = line.partition(":")
    name, value = name.strip(), value.strip()
    if not value:
        # A key with no value opens a block: a list (args) or a mapping (env).
        current.setdefault(name, [] if name == "args" else {})
        return name
    if indent >= 4 and isinstance(current.get(section), dict):
        current[section][name] = value
        return section
    current[name] = {"true": True, "false": False}.get(value, value)
    return None


def parse_config_dump(text: str) -> dict[str, dict]:
    """`hermes config get mcp_servers` output, as a mapping.

    Not a YAML parser and not trying to be -- the same call `_config_shape` in
    ledger_adapters/generic.py makes, and for the same reason: this input is
    machine-generated, two levels deep, and unquoted, and taking on a parser
    dependency for it is how this codebase got burned before.

    `hermes mcp list` is the obvious alternative and is the wrong one: it
    truncates args to a fixed column width, so every entry would look stale.
    """
    servers: dict[str, dict] = {}
    current: dict | None = None
    section: str | None = None

    for raw in text.splitlines():
        if not raw.strip() or raw.strip() == "null":
            continue
        indent = len(raw) - len(raw.lstrip())
        line = raw.strip()

        if indent == 0:
            current = {}
            servers[line.rstrip(":")] = current
            section = None
        elif current is not None:
            section = _dump_line(current, section, indent, line)
    return servers


def _args(root: Path) -> list[str]:
    return ["run", "--project", str(root), "attest-mcp"]


def hermes_servers(root: Path) -> dict[str, dict]:
    """The `mcp_servers` fragment: one entry per surface.

    `enabled: false` is correct and stays. A surface is chosen at launch by a
    person -- that is the finding the split rests on -- and five servers all
    enabled would put every tool back into one session.
    """
    return {
        f"{PREFIX}{name}": {
            "command": "uv",
            "args": _args(root),
            "env": {"ATTEST_TOOLS": name},
            "enabled": False,
        }
        for name in AGENT_SURFACES
    }


def claude_agents(root: Path) -> dict[str, str]:
    """`.claude/agents/<name>.md` bodies, one per surface.

    Same table, different runtime. The tool list is the surface's prefixes
    rather than an enumeration: a new tool in a namespace joins its agent
    without anyone remembering to add it here.
    """
    out = {}
    for name, surface in AGENT_SURFACES.items():
        tools = ", ".join(sorted(surface.prefixes))
        out[name] = (
            "---\n"
            f"name: attestation-{name}\n"
            f"description: {surface.summary}\n"
            f"tools: {tools}\n"
            "---\n\n"
            f"{HEADER}\n\n"
            f"{surface.rationale}\n\n"
            f"Run with `ATTEST_TOOLS={name}`. Tools outside `{tools}` are not\n"
            "registered for this agent: they are absent rather than merely\n"
            "undocumented, because a model that can see a tool will eventually\n"
            "call it.\n"
        )
    return out


def check_hermes(servers: dict[str, dict], root: Path) -> list[Finding]:
    """Compare an on-disk `mcp_servers` mapping against what this table says.

    Compares against the generator, not against a substring. `orphaned` is the
    one a substring check can never find and the reason this exists: an entry
    naming a surface that no longer exists still launches, and
    `register_all` raises on it -- loudly, but at the user's next tool call
    rather than at install time.
    """
    findings: list[Finding] = []
    expected = hermes_servers(root)

    for key, want in expected.items():
        have = servers.get(key)
        if have is None:
            findings.append(
                Finding("missing", key.removeprefix(PREFIX), f"{key} is not in the config")
            )
        elif list(have.get("args", [])) != want["args"]:
            findings.append(
                Finding(
                    "stale",
                    key.removeprefix(PREFIX),
                    f"{key} points at {' '.join(str(a) for a in have.get('args', []))!r},"
                    f" expected {' '.join(want['args'])!r}",
                )
            )
        elif have.get("env", {}).get("ATTEST_TOOLS") != want["env"]["ATTEST_TOOLS"]:
            # ATTEST_TOOLS is the mechanism this whole check exists for -- it
            # is what restricts the surface. An entry with the right path and
            # the wrong binding is the drift most likely to be plausible, and
            # comparing only `args` reported it clean. An entry with no env at
            # all is worse than a missing one: it serves every tool under a
            # name promising four.
            findings.append(
                Finding(
                    "stale",
                    key.removeprefix(PREFIX),
                    f"{key} sets ATTEST_TOOLS="
                    f"{have.get('env', {}).get('ATTEST_TOOLS')!r},"
                    f" expected {want['env']['ATTEST_TOOLS']!r}",
                )
            )

    for key in servers:
        if key == FULL_SERVER or not key.startswith(PREFIX):
            continue
        if key not in expected:
            findings.append(
                Finding(
                    "orphaned",
                    key.removeprefix(PREFIX),
                    f"{key} names a surface that no longer exists"
                    f" (known: {', '.join(sorted(AGENT_SURFACES))})",
                )
            )
    return findings
